# Generated by Django 3.2 on 2022-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clima',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clima',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
